CREATE TABLE PURCHASE_ORDERS (
	IDENTIFIER varchar(15) NOT NULL ,
    TYPE_CODE varchar(15) NOT NULL,
	ACTION_CODE varchar(15) NOT NULL ,
	TOTAL_AMOUNT float NOT NULL
);

INSERT INTO PURCHASE_ORDERS (IDENTIFIER,TYPE_CODE,ACTION_CODE,TOTAL_AMOUNT) VALUES ('abc','DirectShip','Original',3.0);
INSERT INTO PURCHASE_ORDERS (IDENTIFIER,TYPE_CODE,ACTION_CODE,TOTAL_AMOUNT) VALUES ('def','TransferOrder','Change',5.0);